server:
  port: 8080
spring:
  application:
    name: gateway-service

# Config del gateway
gw:
  backends:
    - http://coordinator-service-pwa.internal.politesky-282ace02.westus2.azurecontainerapps.io
    - http://coordinator-service-pwa.internal.politesky-282ace02.westus2.azurecontainerapps.io
  requestTimeoutMillis: 30000



management.endpoints.web.exposure.include: health,info
